# Generated by Django 3.0.3 on 2020-04-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
