# Generated by Django 3.0.3 on 2020-04-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200330_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_added',
            new_name='date_added_to_library',
        ),
    ]
