# Generated by Django 3.0.3 on 2020-04-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_profile'),
        ('catalog', '0007_auto_20200402_2241'),
    ]

    operations = [
    ]
