# Generated by Django 3.0.3 on 2020-04-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_merge_20200407_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='answer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.CharField(blank=True, choices=[('1', 'In what city did you have your first ever birthday party?'), ('2', 'What is the last name of your Science class teacher in high school?'), ('3', 'Which company manufactured your first mobile phone?'), ('4', 'Who was your childhood hero?'), ('5', 'Where was your best family vacation?')], default='m', help_text='Security Question', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Profile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
