# Generated by Django 3.0.3 on 2020-04-15 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200415_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedbooks',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
