# Generated by Django 3.0.3 on 2020-04-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_book_year'),
        ('catalog', '0014_auto_20200414_0018'),
    ]

    operations = [
    ]
