# Generated by Django 3.0.3 on 2020-04-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200415_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedbooks',
            name='book',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='returnedBooks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ReturnedBooks'),
        ),
        migrations.AlterField(
            model_name='returnedbooks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
