# Generated by Django 3.1.2 on 2020-10-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_returnedbooks_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_staff', 'Add Staff Profile'),)},
        ),
    ]
