# Generated by Django 3.0.3 on 2020-10-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200415_0051'),
        ('catalog', '0018_auto_20201013_1614'),
    ]

    operations = [
    ]
